-- =====================================================================
-- FlowForge baseline schema (V1)
--
-- This file is the single source of truth for the database structure.
-- Flyway applies it exactly once and records it in flyway_schema_history.
-- In Phase 3, Hibernate is configured with ddl-auto=validate, so it will
-- VALIDATE its entity mappings against this schema and NEVER alter it.
--
-- Conventions (kept consistent across every table):
--   * Primary keys : BIGINT GENERATED BY DEFAULT AS IDENTITY  (SQL-standard identity;
--                    maps cleanly to JPA @GeneratedValue(strategy = IDENTITY))
--   * Timestamps   : TIMESTAMPTZ (stored in UTC), DEFAULT now()
--   * Enum-like    : VARCHAR + CHECK constraint  (portable, trivially extended, and
--                    maps to JPA @Enumerated(EnumType.STRING); native PG ENUMs are
--                    painful to evolve and to map, so we deliberately avoid them)
--   * Flexible data: JSONB  (typed, indexable JSON for step params / payloads / audit)
--   * Concurrency  : a `version` INTEGER column on every MUTABLE aggregate root, used
--                    later for JPA optimistic locking (@Version)
-- =====================================================================


-- ============================ SECURITY =================================
-- roles: the fixed set of authorization roles. Seeded in V2.
CREATE TABLE roles (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(50)  NOT NULL UNIQUE,
    description VARCHAR(255),
    CONSTRAINT chk_roles_name CHECK (name IN ('ADMIN', 'MANAGER', 'OPERATOR', 'VIEWER'))
);

-- users: application accounts. We store only a password HASH (bcrypt in Phase 9),
-- never a plaintext password.
CREATE TABLE users (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      VARCHAR(100) NOT NULL UNIQUE,
    email         VARCHAR(255) NOT NULL UNIQUE,
    password_hash VARCHAR(255) NOT NULL,
    enabled       BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at    TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version       INTEGER      NOT NULL DEFAULT 0
);

-- user_roles: many-to-many between users and roles. A pure join table with a
-- composite PK (no surrogate id needed - the pair itself is the identity).
CREATE TABLE user_roles (
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    role_id BIGINT NOT NULL REFERENCES roles(id) ON DELETE CASCADE,
    PRIMARY KEY (user_id, role_id)
);


-- ======================= WORKFLOW DEFINITIONS ==========================
-- workflows: the template/definition a user designs. Executions are created FROM it.
CREATE TABLE workflows (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name        VARCHAR(150) NOT NULL,
    description VARCHAR(1000),
    status      VARCHAR(20)  NOT NULL DEFAULT 'DRAFT',
    priority    VARCHAR(20)  NOT NULL DEFAULT 'MEDIUM',
    created_by  BIGINT       REFERENCES users(id) ON DELETE SET NULL,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    version     INTEGER      NOT NULL DEFAULT 0,
    CONSTRAINT chk_workflows_status   CHECK (status   IN ('DRAFT', 'ACTIVE', 'INACTIVE', 'ARCHIVED')),
    CONSTRAINT chk_workflows_priority CHECK (priority IN ('LOW', 'MEDIUM', 'HIGH', 'CRITICAL'))
);
CREATE INDEX idx_workflows_status ON workflows (status);

-- workflow_steps: the ordered units of work in a workflow. NOTE: we intentionally do
-- NOT have a separate `tasks` table - every step IS exactly one task of a given
-- task_type, so a second table would be redundant. `parameters` is the per-step config
-- (e.g. {"to":"a@b.com"} for EMAIL) passed to the engine's TaskContext at run time.
CREATE TABLE workflow_steps (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id BIGINT       NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    name        VARCHAR(150) NOT NULL,
    task_type   VARCHAR(20)  NOT NULL,
    step_order  INTEGER      NOT NULL,
    parameters  JSONB        NOT NULL DEFAULT '{}'::jsonb,
    max_retries INTEGER      NOT NULL DEFAULT 3,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now(),
    CONSTRAINT chk_steps_task_type   CHECK (task_type IN ('EMAIL', 'WEBHOOK', 'APPROVAL', 'CUSTOM')),
    CONSTRAINT chk_steps_max_retries CHECK (max_retries >= 0),
    CONSTRAINT uq_steps_workflow_order UNIQUE (workflow_id, step_order)
);
CREATE INDEX idx_steps_workflow ON workflow_steps (workflow_id);

-- step_dependencies: edges of the dependency DAG. A step may depend on other steps in
-- the SAME workflow; the engine (Phase 6) topologically sorts these to decide what can
-- run in parallel. Modelled as its own table (not a column) because a step can have
-- MANY predecessors - a classic many-to-many self relationship on workflow_steps.
CREATE TABLE step_dependencies (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    step_id            BIGINT NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
    depends_on_step_id BIGINT NOT NULL REFERENCES workflow_steps(id) ON DELETE CASCADE,
    CONSTRAINT uq_step_dep          UNIQUE (step_id, depends_on_step_id),
    CONSTRAINT chk_step_dep_no_self CHECK (step_id <> depends_on_step_id)
);
CREATE INDEX idx_step_dep_step ON step_dependencies (step_id);


-- ========================== EXECUTION STATE ============================
-- workflow_executions: one run of a workflow. correlation_id ties together all of its
-- task_executions and log lines for tracing.
CREATE TABLE workflow_executions (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_id    BIGINT      NOT NULL REFERENCES workflows(id) ON DELETE CASCADE,
    status         VARCHAR(20) NOT NULL DEFAULT 'PENDING',
    correlation_id VARCHAR(64) NOT NULL UNIQUE,
    triggered_by   BIGINT      REFERENCES users(id) ON DELETE SET NULL,
    started_at     TIMESTAMPTZ,
    finished_at    TIMESTAMPTZ,
    created_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at     TIMESTAMPTZ NOT NULL DEFAULT now(),
    version        INTEGER     NOT NULL DEFAULT 0,
    CONSTRAINT chk_wf_exec_status CHECK (status IN ('PENDING', 'RUNNING', 'SUCCEEDED', 'FAILED', 'CANCELLED'))
);
CREATE INDEX idx_wf_exec_status   ON workflow_executions (status);
CREATE INDEX idx_wf_exec_workflow ON workflow_executions (workflow_id);

-- task_executions: one attempt-tracked run of a single step within a workflow_execution.
-- Retry state (attempt / max_attempts / next_retry_at / last_error) lives HERE as
-- columns. We deliberately did NOT create a separate `retry_queue` table: that would
-- duplicate this row's identity and state. The scheduler simply polls this table for
-- rows that are due (see the composite index below).
CREATE TABLE task_executions (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    workflow_execution_id BIGINT      NOT NULL REFERENCES workflow_executions(id) ON DELETE CASCADE,
    workflow_step_id      BIGINT      NOT NULL REFERENCES workflow_steps(id)      ON DELETE CASCADE,
    status                VARCHAR(24) NOT NULL DEFAULT 'PENDING',
    attempt               INTEGER     NOT NULL DEFAULT 0,
    max_attempts          INTEGER     NOT NULL DEFAULT 4,
    next_retry_at         TIMESTAMPTZ,
    last_error            TEXT,
    output                JSONB,
    started_at            TIMESTAMPTZ,
    finished_at           TIMESTAMPTZ,
    created_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at            TIMESTAMPTZ NOT NULL DEFAULT now(),
    version               INTEGER     NOT NULL DEFAULT 0,
    CONSTRAINT chk_task_exec_status CHECK (status IN (
        'PENDING', 'RUNNING', 'SUCCEEDED', 'RETRYABLE_FAILURE',
        'PERMANENT_FAILURE', 'DEAD_LETTER', 'PENDING_APPROVAL', 'CANCELLED')),
    CONSTRAINT chk_task_exec_attempt CHECK (attempt >= 0 AND attempt <= max_attempts)
);
-- This composite index is the one that matters most for throughput: it powers the
-- retry scheduler's hot query
--   SELECT ... FROM task_executions WHERE status = 'RETRYABLE_FAILURE' AND next_retry_at <= now()
CREATE INDEX idx_task_exec_retry   ON task_executions (status, next_retry_at);
CREATE INDEX idx_task_exec_wf_exec ON task_executions (workflow_execution_id);


-- =========================== DEAD LETTER ===============================
-- dead_letter_tasks: tasks that exhausted all retries or failed permanently. Unlike the
-- retry state above, a dedicated table IS justified here: dead letters have a different
-- lifecycle (manual inspection + replay), often a different retention policy, and we
-- want to scan/report on them WITHOUT touching the large, hot task_executions table.
CREATE TABLE dead_letter_tasks (
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    task_execution_id     BIGINT      NOT NULL REFERENCES task_executions(id)      ON DELETE CASCADE,
    workflow_execution_id BIGINT      NOT NULL REFERENCES workflow_executions(id)  ON DELETE CASCADE,
    task_type             VARCHAR(20) NOT NULL,
    payload               JSONB,
    last_error            TEXT,
    attempts              INTEGER     NOT NULL,
    failed_at             TIMESTAMPTZ NOT NULL DEFAULT now(),
    replayed              BOOLEAN     NOT NULL DEFAULT FALSE,
    replayed_at           TIMESTAMPTZ,
    CONSTRAINT chk_dlt_task_type CHECK (task_type IN ('EMAIL', 'WEBHOOK', 'APPROVAL', 'CUSTOM')),
    CONSTRAINT uq_dlt_task_exec  UNIQUE (task_execution_id)
);
CREATE INDEX idx_dlt_replayed ON dead_letter_tasks (replayed);


-- ============================== AUDIT ==================================
-- audit_logs: append-only record of significant actions. old_value/new_value capture a
-- JSON snapshot around a change (e.g. workflow status DRAFT -> ACTIVE). actor is NULL
-- for system-initiated actions (e.g. the scheduler).
CREATE TABLE audit_logs (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    actor       VARCHAR(100),
    action      VARCHAR(80)  NOT NULL,
    entity_type VARCHAR(80)  NOT NULL,
    entity_id   BIGINT,
    old_value   JSONB,
    new_value   JSONB,
    metadata    JSONB,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT now()
);
CREATE INDEX idx_audit_entity  ON audit_logs (entity_type, entity_id);
CREATE INDEX idx_audit_created ON audit_logs (created_at);
